import { supabase } from './supabase.js'
import { showToast, confirmAction, promptAction } from './feedback.js'
import { applyTenantFilter, canAccessAllDepartments, getAccessibleProfiles } from './access-control.js'

const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const esc = (v = '') => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]))
const val = id => document.getElementById(id)?.value?.trim() || ''
const num = id => Number(document.getElementById(id)?.value || 0)
const clientId = () => window.currentUser?.client_id || null

function scoped(query, opts = {}) { return applyTenantFilter(query, { user: window.currentUser, userColumn: null, ...opts }) }
function content() { return document.getElementById('content') }
function isPayrollAllowed() { return window.canUsePackageFeature?.('payroll') !== false }
function guard() { if (isPayrollAllowed()) return true; content().innerHTML = `<div class="card"><h2><i class="fa fa-lock"></i> Payroll terkunci</h2><p>Payroll hanya tersedia untuk paket Standard dan Pro.</p></div>`; return false }

async function loadComponents(activeOnly = false) {
  let q = scoped(supabase.from('payroll_components').select('*').order('sort_order').order('component_name'))
  if (activeOnly) q = q.eq('is_active', true)
  const { data, error } = await q
  if (error) throw error
  return data || []
}
async function loadTemplates() { const { data, error } = await scoped(supabase.from('payroll_templates').select('*').order('template_name')); if (error) throw error; return data || [] }

export async function renderPayroll(tab = 'dashboard') {
  if (!guard()) return
  const tabs = ['dashboard','components','templates','periods','processing','slips','history']
  const labels = { dashboard:'Dashboard', components:'Payroll Components', templates:'Payroll Templates', periods:'Payroll Periods', processing:'Payroll Processing', slips:'Salary Slips', history:'Payroll History' }
  content().innerHTML = `<div class="page-header"><div><h2><i class="fa fa-money-check-dollar"></i> Payroll</h2><p>Kelola komponen, template, periode, proses payroll, slip gaji, dan riwayat.</p></div></div><div class="card" style="padding:12px;margin-bottom:12px;display:flex;gap:8px;flex-wrap:wrap;">${tabs.map(t=>`<button class="${t===tab?'btn-primary':'btn-secondary'} btn-sm" onclick="window.renderPayroll('${t}')">${labels[t]}</button>`).join('')}</div><div id="payrollBody" class="card" style="padding:16px;overflow-x:auto;">Memuat...</div>`
  const fn = { dashboard: renderPayrollDashboard, components: renderPayrollComponents, templates: renderPayrollTemplates, periods: renderPayrollPeriods, processing: renderPayrollProcessing, slips: renderPayrollSlips, history: renderPayrollHistory }[tab]
  await fn()
}

async function renderPayrollDashboard() {
  const [components, templates, periods] = await Promise.all([loadComponents(), loadTemplates(), scoped(supabase.from('payroll_periods').select('*'))])
  document.getElementById('payrollBody').innerHTML = `<div class="stats-grid"><div class="stat-card"><div class="stat-label">Komponen</div><div class="stat-value">${components.length}</div></div><div class="stat-card"><div class="stat-label">Template</div><div class="stat-value">${templates.length}</div></div><div class="stat-card"><div class="stat-label">Periode</div><div class="stat-value">${periods.data?.length || 0}</div></div></div><p style="color:var(--text-muted);font-size:.85rem;line-height:1.6;">Version 1 menghitung komponen payroll saja. Arsitektur tabel detail mendukung sumber perhitungan lain di fase berikutnya.</p>`
}

async function renderPayrollComponents() {
  const rows = await loadComponents()
  document.getElementById('payrollBody').innerHTML = `<div style="display:flex;justify-content:space-between;gap:10px;margin-bottom:12px;"><h3>Master Payroll Components</h3><button class="btn-primary btn-sm" onclick="window.openPayrollComponentForm()"><i class="fa fa-plus"></i> Add Component</button></div>${table(['Code','Name','Type','Input','Sort','Active','Actions'], rows.map(r=>[esc(r.code),esc(r.component_name),esc(r.type),esc(r.input_type),r.sort_order,r.is_active?'Yes':'No',`<button class="action-btn edit" onclick="window.openPayrollComponentForm('${r.id}')">Edit</button> <button class="action-btn delete" onclick="window.deletePayrollComponent('${r.id}')">Delete</button>`]))}`
}
window.openPayrollComponentForm = async id => { const row = id ? (await supabase.from('payroll_components').select('*').eq('id', id).maybeSingle()).data : {}; window.showUserModal(`<div class="modal-header"><h3>${id?'Edit':'Add'} Payroll Component</h3><button class="modal-close" onclick="closeUserModal()">×</button></div><div class="field"><label>Code</label><input id="pcCode" value="${esc(row?.code||'')}"></div><div class="field"><label>Name</label><input id="pcName" value="${esc(row?.component_name||'')}"></div><div class="field"><label>Type</label><select id="pcType"><option ${row?.type==='Income'?'selected':''}>Income</option><option ${row?.type==='Deduction'?'selected':''}>Deduction</option></select></div><div class="field"><label>Input Type</label><select id="pcInput"><option ${row?.input_type==='Fixed Amount'?'selected':''}>Fixed Amount</option><option ${row?.input_type==='Manual Amount'?'selected':''}>Manual Amount</option></select></div><div class="field"><label>Sort Order</label><input type="number" id="pcSort" value="${row?.sort_order||0}"></div><div class="field"><label>Description</label><textarea id="pcDesc">${esc(row?.description||'')}</textarea></div><label><input type="checkbox" id="pcActive" ${row?.is_active!==false?'checked':''}> Active</label><div class="modal-actions"><button class="btn-secondary" onclick="closeUserModal()">Cancel</button><button class="btn-primary" onclick="window.savePayrollComponent('${id||''}')">Save</button></div>`) }
window.savePayrollComponent = async id => { const payload = { code: val('pcCode'), component_name: val('pcName'), type: val('pcType'), input_type: val('pcInput'), sort_order: num('pcSort'), description: val('pcDesc'), is_active: document.getElementById('pcActive')?.checked, client_id: clientId() }; const q = id ? supabase.from('payroll_components').update(payload).eq('id', id) : supabase.from('payroll_components').insert(payload); const { error } = await q; if (error) return showToast(error.message,'error'); closeUserModal(); showToast('Komponen tersimpan','success'); renderPayroll('components') }
window.deletePayrollComponent = async id => { if (!(await confirmAction('Hapus komponen payroll?','Hapus'))) return; const { error } = await supabase.from('payroll_components').delete().eq('id', id); if (error) return showToast(error.message,'error'); renderPayroll('components') }

async function renderPayrollTemplates() {
  const rows = await loadTemplates()
  document.getElementById('payrollBody').innerHTML = `<div style="display:flex;justify-content:space-between;gap:10px;margin-bottom:12px;"><h3>Payroll Templates</h3><button class="btn-primary btn-sm" onclick="window.openPayrollTemplateForm()">Add Template</button></div>${table(['Template','Description','Active','Actions'], rows.map(r=>[esc(r.template_name),esc(r.description),r.is_active?'Yes':'No',`<button class="action-btn view" onclick="window.managePayrollTemplate('${r.id}')">Components</button> <button class="action-btn edit" onclick="window.openPayrollTemplateForm('${r.id}')">Rename</button> <button class="action-btn edit" onclick="window.duplicatePayrollTemplate('${r.id}')">Duplicate</button> <button class="action-btn delete" onclick="window.deletePayrollTemplate('${r.id}')">Delete</button>`]))}`
}
window.openPayrollTemplateForm = async id => { const row = id ? (await supabase.from('payroll_templates').select('*').eq('id', id).maybeSingle()).data : {}; window.showUserModal(`<div class="modal-header"><h3>${id?'Edit':'Add'} Template</h3><button class="modal-close" onclick="closeUserModal()">×</button></div><div class="field"><label>Template Name</label><input id="ptName" value="${esc(row?.template_name||'')}"></div><div class="field"><label>Description</label><textarea id="ptDesc">${esc(row?.description||'')}</textarea></div><label><input type="checkbox" id="ptActive" ${row?.is_active!==false?'checked':''}> Active</label><div class="modal-actions"><button class="btn-secondary" onclick="closeUserModal()">Cancel</button><button class="btn-primary" onclick="window.savePayrollTemplate('${id||''}')">Save</button></div>`) }
window.savePayrollTemplate = async id => { const payload = { template_name: val('ptName'), description: val('ptDesc'), is_active: document.getElementById('ptActive')?.checked, client_id: clientId() }; const q = id ? supabase.from('payroll_templates').update(payload).eq('id', id) : supabase.from('payroll_templates').insert(payload); const { error } = await q; if (error) return showToast(error.message,'error'); closeUserModal(); renderPayroll('templates') }
window.duplicatePayrollTemplate = async id => { const name = await promptAction('Nama template duplikat:', 'Copy Template'); if (!name) return; const { data:t } = await supabase.from('payroll_templates').select('*').eq('id', id).single(); const { data:n, error } = await supabase.from('payroll_templates').insert({ client_id:t.client_id, template_name:name, description:t.description, is_active:t.is_active }).select().single(); if (error) return showToast(error.message,'error'); const { data: comps } = await supabase.from('payroll_template_components').select('component_id,component_value,sort_order,is_active').eq('template_id', id); if (comps?.length) await supabase.from('payroll_template_components').insert(comps.map(c=>({...c,template_id:n.id}))); renderPayroll('templates') }
window.deletePayrollTemplate = async id => { if (await confirmAction('Hapus template payroll?','Hapus')) { const { error } = await supabase.from('payroll_templates').delete().eq('id', id); if (error) showToast(error.message,'error'); else renderPayroll('templates') } }
window.managePayrollTemplate = async id => { const [tc, comps] = await Promise.all([supabase.from('payroll_template_components').select('*, payroll_components(*)').eq('template_id', id).order('sort_order'), loadComponents(true)]); window.showUserModal(`<div class="modal-header"><h3>Template Components</h3><button class="modal-close" onclick="closeUserModal()">×</button></div>${table(['Component','Value','Actions'], (tc.data||[]).map(r=>[esc(r.payroll_components?.component_name), money.format(r.component_value||0), `<button class="action-btn edit" onclick="window.editTemplateComponent('${r.id}', '${id}', ${r.component_value||0})">Edit</button> <button class="action-btn delete" onclick="window.removeTemplateComponent('${r.id}', '${id}')">Remove</button>`]))}<div class="field"><label>Add Component</label><select id="tplCompId">${comps.map(c=>`<option value="${c.id}">${esc(c.component_name)}</option>`)}</select></div><div class="field"><label>Value</label><input type="number" id="tplCompValue" value="0"></div><button class="btn-primary" onclick="window.addTemplateComponent('${id}')">Add</button>`) }
window.addTemplateComponent = async id => { const { error } = await supabase.from('payroll_template_components').insert({ template_id:id, component_id:val('tplCompId'), component_value:num('tplCompValue') }); if (error) return showToast(error.message,'error'); await askTemplatePropagation(id); managePayrollTemplate(id) }
window.editTemplateComponent = async (rowId, tplId, old) => { const v = await promptAction('Nilai komponen:', String(old)); if (v === null) return; const { error } = await supabase.from('payroll_template_components').update({ component_value:Number(v) }).eq('id', rowId); if (error) return showToast(error.message,'error'); await askTemplatePropagation(tplId); managePayrollTemplate(tplId) }
window.removeTemplateComponent = async (rowId, tplId) => { if (await confirmAction('Remove component?','Remove')) { await supabase.from('payroll_template_components').delete().eq('id', rowId); await askTemplatePropagation(tplId); managePayrollTemplate(tplId) } }
async function askTemplatePropagation(templateId) { const choice = await promptAction('Apply changes to: existing | new | selected. Ketik existing untuk update karyawan yang masih memakai Template value.', 'new'); if (String(choice).toLowerCase() === 'existing') await applyTemplateToEmployees(templateId) }

async function renderPayrollPeriods() { const { data } = await scoped(supabase.from('payroll_periods').select('*').order('start_date',{ascending:false})); document.getElementById('payrollBody').innerHTML = `<div style="display:flex;justify-content:space-between;margin-bottom:12px;"><h3>Payroll Periods</h3><button class="btn-primary btn-sm" onclick="window.openPayrollPeriodForm()">Add Period</button></div>${table(['Name','Start','End','Status','Actions'], (data||[]).map(r=>[esc(r.period_name),r.start_date,r.end_date,r.status,`<button class="action-btn edit" onclick="window.openPayrollPeriodForm('${r.id}')">Edit</button> <button class="action-btn delete" onclick="window.deletePayrollPeriod('${r.id}')">Delete</button>`]))}` }
window.openPayrollPeriodForm = async id => { const row = id ? (await supabase.from('payroll_periods').select('*').eq('id',id).maybeSingle()).data : {}; window.showUserModal(`<div class="modal-header"><h3>Payroll Period</h3><button class="modal-close" onclick="closeUserModal()">×</button></div><div class="field"><label>Name</label><input id="ppName" value="${esc(row?.period_name||'')}"></div><div class="field"><label>Start</label><input type="date" id="ppStart" value="${row?.start_date||''}"></div><div class="field"><label>End</label><input type="date" id="ppEnd" value="${row?.end_date||''}"></div><div class="field"><label>Status</label><select id="ppStatus">${['Draft','Processing','Approved','Paid','Closed'].map(s=>`<option ${row?.status===s?'selected':''}>${s}</option>`)}</select></div><div class="modal-actions"><button class="btn-secondary" onclick="closeUserModal()">Cancel</button><button class="btn-primary" onclick="window.savePayrollPeriod('${id||''}')">Save</button></div>`) }
window.savePayrollPeriod = async id => { const payload = { client_id:clientId(), period_name:val('ppName'), start_date:val('ppStart'), end_date:val('ppEnd'), status:val('ppStatus') }; const q = id ? supabase.from('payroll_periods').update(payload).eq('id',id) : supabase.from('payroll_periods').insert(payload); const { error } = await q; if (error) return showToast(error.message,'error'); closeUserModal(); renderPayroll('periods') }
window.deletePayrollPeriod = async id => { if (await confirmAction('Hapus periode?','Hapus')) { const { error } = await supabase.from('payroll_periods').delete().eq('id', id); if (error) showToast(error.message,'error'); else renderPayroll('periods') } }

async function renderPayrollProcessing() { const [periods, employees] = await Promise.all([scoped(supabase.from('payroll_periods').select('*').order('start_date',{ascending:false})), getAccessibleProfiles(window.currentUser,{activeOnly:true,select:'id,nama_lengkap,departemen,department_id,client_id'})]); document.getElementById('payrollBody').innerHTML = `<h3>Payroll Processing</h3><div class="field"><label>Payroll Period</label><select id="procPeriod">${(periods.data||[]).map(p=>`<option value="${p.id}">${esc(p.period_name)}</option>`)}</select></div><div class="field"><label>Employee</label><select id="procEmployee"><option value="">All Employees</option>${employees.map(e=>`<option value="${e.id}">${esc(e.nama_lengkap)}</option>`)}</select></div><button class="btn-primary" onclick="window.generatePayroll()"><i class="fa fa-gears"></i> Generate Payroll</button>` }
window.generatePayroll = async () => { const periodId = val('procPeriod'); const employeeId = val('procEmployee'); const employees = employeeId ? [employeeId] : (await getAccessibleProfiles(window.currentUser,{activeOnly:true,select:'id'})).map(e=>e.id); for (const eid of employees) await generateEmployeePayroll(periodId, eid); showToast('Payroll generated','success'); renderPayroll('slips') }
async function generateEmployeePayroll(periodId, employeeId) { const { data: comps } = await supabase.from('employee_payroll_components').select('*, payroll_components(*)').eq('employee_id', employeeId).eq('is_active', true); const income=(comps||[]).filter(c=>c.payroll_components?.type==='Income').reduce((s,c)=>s+Number(c.component_value||0),0); const deduction=(comps||[]).filter(c=>c.payroll_components?.type==='Deduction').reduce((s,c)=>s+Number(c.component_value||0),0); const { data:payroll } = await supabase.from('payroll_runs').upsert({ client_id:clientId(), period_id:periodId, employee_id:employeeId, total_income:income, total_deduction:deduction, net_salary:income-deduction, status:'Draft' }, { onConflict:'period_id,employee_id' }).select().single(); await supabase.from('payroll_run_details').delete().eq('payroll_id', payroll.id); if (comps?.length) await supabase.from('payroll_run_details').insert(comps.map(c=>({ payroll_id:payroll.id, component_id:c.component_id, component_name:c.payroll_components?.component_name, type:c.payroll_components?.type, amount:c.component_value, source:c.source }))) }
async function renderPayrollSlips() { const { data } = await scoped(supabase.from('payroll_runs').select('*, payroll_periods(period_name), profiles(nama_lengkap)').order('created_at',{ascending:false})); document.getElementById('payrollBody').innerHTML = `<h3>Salary Slips</h3>${table(['Employee','Period','Income','Deduction','Net','Actions'], (data||[]).map(r=>[esc(r.profiles?.nama_lengkap),esc(r.payroll_periods?.period_name),money.format(r.total_income||0),money.format(r.total_deduction||0),money.format(r.net_salary||0),`<button class="action-btn view" onclick="window.viewSalarySlip('${r.id}')">View/PDF</button>`]))}` }
window.viewSalarySlip = async id => { const { data:r } = await supabase.from('payroll_runs').select('*, payroll_periods(period_name), profiles(nama_lengkap), payroll_run_details(*)').eq('id',id).single(); window.showUserModal(`<div class="modal-header"><h3>Salary Slip</h3><button class="modal-close" onclick="closeUserModal()">×</button></div><div id="salarySlipPrint"><h3>${esc(r.profiles?.nama_lengkap)}</h3><p>${esc(r.payroll_periods?.period_name)}</p>${table(['Component','Type','Source','Amount'], (r.payroll_run_details||[]).map(d=>[esc(d.component_name),esc(d.type),esc(d.source),money.format(d.amount||0)]))}<h3>Net Salary: ${money.format(r.net_salary||0)}</h3></div><button class="btn-primary" onclick="window.print()">Export PDF</button>`) }
async function renderPayrollHistory() { await renderPayrollSlips() }

export async function renderEmployeePayroll(employee) { if (!guard()) return ''; const [templates, comps, active] = await Promise.all([loadTemplates(), loadComponents(true), supabase.from('employee_payroll_components').select('*, payroll_components(*), payroll_templates(template_name)').eq('employee_id', employee.id).order('sort_order')]); return `<div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:12px;"><h4>Payroll Configuration</h4><div><select id="empTemplateId"><option value="">Assign Template</option>${templates.map(t=>`<option value="${t.id}">${esc(t.template_name)}</option>`)}</select><button class="btn-primary btn-sm" onclick="window.assignEmployeePayrollTemplate('${employee.id}')">Assign Template</button></div></div>${table(['Component','Source','Value','Actions'], (active.data||[]).map(r=>[esc(r.payroll_components?.component_name),esc(r.source),money.format(r.component_value||0),`<button class="action-btn edit" onclick="window.editEmployeePayrollComponent('${r.id}', ${r.component_value||0})">Override Value</button> <button class="action-btn view" onclick="window.restoreEmployeePayrollComponent('${r.id}')">Restore Template</button> <button class="action-btn delete" onclick="window.deleteEmployeePayrollComponent('${r.id}', '${employee.id}')">Delete</button>`]))}<div class="field"><label>Add Component</label><select id="empCompId">${comps.map(c=>`<option value="${c.id}">${esc(c.component_name)}</option>`)}</select></div><div class="field"><label>Value</label><input type="number" id="empCompValue" value="0"></div><button class="btn-primary btn-sm" onclick="window.addEmployeePayrollComponent('${employee.id}')">Add Component</button>` }
window.assignEmployeePayrollTemplate = async employeeId => { await applyTemplateToEmployees(val('empTemplateId'), [employeeId]); showToast('Template assigned','success'); window.openDetailKaryawan(employeeId, 'payroll') }
window.addEmployeePayrollComponent = async employeeId => { await supabase.from('employee_payroll_components').insert({ employee_id:employeeId, component_id:val('empCompId'), component_value:num('empCompValue'), source:'Override', is_override:true, is_active:true }); window.openDetailKaryawan(employeeId, 'payroll') }
window.editEmployeePayrollComponent = async (id, old) => { const v = await promptAction('Override value:', String(old)); if (v === null) return; await supabase.from('employee_payroll_components').update({ component_value:Number(v), source:'Override', is_override:true }).eq('id', id); window.openDetailKaryawan(window._currentDetailEmployeeId, 'payroll') }
window.restoreEmployeePayrollComponent = async id => { const { data:r } = await supabase.from('employee_payroll_components').select('template_component_id,employee_id').eq('id',id).single(); if (r?.template_component_id) { const { data:t } = await supabase.from('payroll_template_components').select('component_value').eq('id',r.template_component_id).single(); await supabase.from('employee_payroll_components').update({ component_value:t.component_value, source:'Template', is_override:false }).eq('id', id) } window.openDetailKaryawan(r.employee_id, 'payroll') }
window.deleteEmployeePayrollComponent = async (id, employeeId) => { await supabase.from('employee_payroll_components').delete().eq('id', id); window.openDetailKaryawan(employeeId, 'payroll') }
async function applyTemplateToEmployees(templateId, employeeIds = null) {
  const { data: tcs } = await supabase.from('payroll_template_components').select('*').eq('template_id', templateId)
  const ids = employeeIds || (await supabase.from('employee_payroll_profiles').select('employee_id').eq('template_id', templateId)).data?.map(r => r.employee_id) || []
  for (const employeeId of ids) {
    await supabase.from('employee_payroll_profiles').upsert({ employee_id: employeeId, template_id: templateId }, { onConflict: 'employee_id' })
    for (const c of (tcs || [])) {
      const { data: existing } = await supabase.from('employee_payroll_components').select('id,is_override').eq('employee_id', employeeId).eq('component_id', c.component_id).maybeSingle()
      if (existing?.is_override) continue
      if (existing?.id) {
        await supabase.from('employee_payroll_components').update({ template_id: templateId, template_component_id: c.id, component_value: c.component_value, source: 'Template', is_override: false, is_active: c.is_active }).eq('id', existing.id)
      } else {
        await supabase.from('employee_payroll_components').insert({ employee_id: employeeId, template_id: templateId, template_component_id: c.id, component_id: c.component_id, component_value: c.component_value, source: 'Template', is_override: false, is_active: c.is_active })
      }
    }
  }
}

function table(head, rows) { return `<div class="table-responsive"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}" style="text-align:center;color:var(--text-muted);padding:18px;">Belum ada data.</td></tr>`}</tbody></table></div>` }

window.renderPayroll = renderPayroll
