create table if not exists public.payroll_run_details (
  id uuid primary key default gen_random_uuid(),
  payroll_id uuid not null references public.payroll_runs(id) on delete cascade,
  component_id uuid references public.payroll_components(id) on delete set null,
  component_name text not null,
  type text not null check (type in ('Income','Deduction')),
  source text not null check (source in ('Template','Override','System')),
  amount numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_payroll_run_details_payroll on public.payroll_run_details(payroll_id);
comment on table public.payroll_run_details is 'Salary slip line items generated from employee payroll components; future calculation sources can add System rows.';

-- Browser API protection: enable RLS on every payroll table. Policies mirror app scope:
-- super_admin can access all; admin_all/admin_hr can manage same-client rows; admin can read/process employees in same department where applicable; staff can read own generated slips/details only.
alter table public.payroll_components enable row level security;
alter table public.payroll_templates enable row level security;
alter table public.payroll_template_components enable row level security;
alter table public.employee_payroll_profiles enable row level security;
alter table public.employee_payroll_components enable row level security;
alter table public.payroll_periods enable row level security;
alter table public.payroll_runs enable row level security;
alter table public.payroll_run_details enable row level security;

create policy "payroll_components_admin" on public.payroll_components for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'super_admin' or (p.id = auth.uid() and p.role in ('admin_all','admin_hr') and public.payroll_components.client_id = p.client_id))) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'super_admin' or (p.id = auth.uid() and p.role in ('admin_all','admin_hr') and public.payroll_components.client_id = p.client_id)));
create policy "payroll_templates_admin" on public.payroll_templates for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'super_admin' or (p.id = auth.uid() and p.role in ('admin_all','admin_hr') and public.payroll_templates.client_id = p.client_id))) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'super_admin' or (p.id = auth.uid() and p.role in ('admin_all','admin_hr') and public.payroll_templates.client_id = p.client_id)));
create policy "payroll_template_components_admin" on public.payroll_template_components for all to authenticated using (exists (select 1 from public.profiles p join public.payroll_templates t on t.id = public.payroll_template_components.template_id where p.id = auth.uid() and (p.role = 'super_admin' or (p.role in ('admin_all','admin_hr') and t.client_id = p.client_id)))) with check (exists (select 1 from public.profiles p join public.payroll_templates t on t.id = public.payroll_template_components.template_id where p.id = auth.uid() and (p.role = 'super_admin' or (p.role in ('admin_all','admin_hr') and t.client_id = p.client_id))));
create policy "employee_payroll_profiles_scoped" on public.employee_payroll_profiles for all to authenticated using (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.employee_payroll_profiles.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id) or target.id = actor.id))) with check (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.employee_payroll_profiles.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id))));
create policy "employee_payroll_components_scoped" on public.employee_payroll_components for all to authenticated using (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.employee_payroll_components.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id) or target.id = actor.id))) with check (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.employee_payroll_components.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id))));
create policy "payroll_periods_admin" on public.payroll_periods for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and (p.role = 'super_admin' or (p.role in ('admin_all','admin_hr') and public.payroll_periods.client_id = p.client_id)))) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and (p.role = 'super_admin' or (p.role in ('admin_all','admin_hr') and public.payroll_periods.client_id = p.client_id))));
create policy "payroll_runs_scoped" on public.payroll_runs for all to authenticated using (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.payroll_runs.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id) or target.id = actor.id))) with check (exists (select 1 from public.profiles actor join public.profiles target on target.id = public.payroll_runs.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id))));
create policy "payroll_run_details_scoped" on public.payroll_run_details for all to authenticated using (exists (select 1 from public.profiles actor join public.payroll_runs pr on pr.id = public.payroll_run_details.payroll_id join public.profiles target on target.id = pr.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id) or target.id = actor.id))) with check (exists (select 1 from public.profiles actor join public.payroll_runs pr on pr.id = public.payroll_run_details.payroll_id join public.profiles target on target.id = pr.employee_id where actor.id = auth.uid() and (actor.role = 'super_admin' or (actor.role in ('admin_all','admin_hr') and target.client_id = actor.client_id) or (actor.role = 'admin' and target.client_id = actor.client_id and target.department_id is not distinct from actor.department_id))));
